# Synchronizes .netconfig-configured files with dotnet-file
name: sync
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  DOTNET_NOLOGO: true

jobs:
  sync:
    runs-on: windows-latest
    continue-on-error: true
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main

      - name: 🔄 sync
        shell: pwsh
        run: |
          dotnet tool update -g dotnet-gcm
          dotnet gcm store --protocol=https --host=github.com --username=$env:GITHUB_ACTOR --password=${{ secrets.GITHUB_TOKEN }}
          gh auth status

          dotnet tool update -g dotnet-file
          dotnet file sync -c:$env:TEMP\dotnet-file.md
          if (test-path $env:TEMP\dotnet-file.md) {
            echo 'CHANGES<<EOF' >> $env:GITHUB_ENV
            cat $env:TEMP\dotnet-file.md >> $env:GITHUB_ENV
            echo 'EOF' >> $env:GITHUB_ENV
            cat $env:TEMP\dotnet-file.md
          } else {
            echo 'No changelog was generated'
          }

      - name: ✍ pull request
        uses: peter-evans/create-pull-request@v4
        with:
          base: main
          branch: dotnet-file-sync
          delete-branch: true
          labels: dependencies
          commit-message: ⬆️ Bump files with dotnet-file sync
          
            ${{ env.CHANGES }}
          title: "⬆️ Bump files with dotnet-file sync"
          body: ${{ env.CHANGES }}